# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SBSPortInfo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(777, 427)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(370, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 751, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iplineEdit_AWG = QtWidgets.QLineEdit(self.layoutWidget)
        self.iplineEdit_AWG.setObjectName("iplineEdit_AWG")
        self.horizontalLayout_2.addWidget(self.iplineEdit_AWG)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iplineEdit_EVNA = QtWidgets.QLineEdit(self.layoutWidget)
        self.iplineEdit_EVNA.setObjectName("iplineEdit_EVNA")
        self.horizontalLayout.addWidget(self.iplineEdit_EVNA)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iplineEdit_OSA = QtWidgets.QLineEdit(self.layoutWidget)
        self.iplineEdit_OSA.setObjectName("iplineEdit_OSA")
        self.horizontalLayout_3.addWidget(self.iplineEdit_OSA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_EDFA1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_EDFA1.setObjectName("comboBox_EDFA1")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.comboBox_EDFA1.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_EDFA1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.comboBox_TLS = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_TLS.setObjectName("comboBox_TLS")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.comboBox_TLS.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_TLS)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_EDFA2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_EDFA2.setObjectName("comboBox_EDFA2")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.comboBox_EDFA2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_EDFA2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_DC = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_DC.setObjectName("comboBox_DC")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.comboBox_DC.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_DC)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "AWG"))
        self.label_2.setText(_translate("Dialog", "EVNA"))
        self.label_3.setText(_translate("Dialog", "OSA"))
        self.label_4.setText(_translate("Dialog", "EDFA1"))
        self.comboBox_EDFA1.setItemText(0, _translate("Dialog", "COM1"))
        self.comboBox_EDFA1.setItemText(1, _translate("Dialog", "COM2"))
        self.comboBox_EDFA1.setItemText(2, _translate("Dialog", "COM3"))
        self.comboBox_EDFA1.setItemText(3, _translate("Dialog", "COM4"))
        self.comboBox_EDFA1.setItemText(4, _translate("Dialog", "COM5"))
        self.comboBox_EDFA1.setItemText(5, _translate("Dialog", "COM6"))
        self.comboBox_EDFA1.setItemText(6, _translate("Dialog", "COM7"))
        self.comboBox_EDFA1.setItemText(7, _translate("Dialog", "COM8"))
        self.comboBox_EDFA1.setItemText(8, _translate("Dialog", "COM9"))
        self.label_7.setText(_translate("Dialog", "TLS"))
        self.comboBox_TLS.setItemText(0, _translate("Dialog", "COM1"))
        self.comboBox_TLS.setItemText(1, _translate("Dialog", "COM2"))
        self.comboBox_TLS.setItemText(2, _translate("Dialog", "COM3"))
        self.comboBox_TLS.setItemText(3, _translate("Dialog", "COM4"))
        self.comboBox_TLS.setItemText(4, _translate("Dialog", "COM5"))
        self.comboBox_TLS.setItemText(5, _translate("Dialog", "COM6"))
        self.comboBox_TLS.setItemText(6, _translate("Dialog", "COM7"))
        self.comboBox_TLS.setItemText(7, _translate("Dialog", "COM8"))
        self.comboBox_TLS.setItemText(8, _translate("Dialog", "COM9"))
        self.label_5.setText(_translate("Dialog", "EDFA2"))
        self.comboBox_EDFA2.setItemText(0, _translate("Dialog", "COM1"))
        self.comboBox_EDFA2.setItemText(1, _translate("Dialog", "COM2"))
        self.comboBox_EDFA2.setItemText(2, _translate("Dialog", "COM3"))
        self.comboBox_EDFA2.setItemText(3, _translate("Dialog", "COM4"))
        self.comboBox_EDFA2.setItemText(4, _translate("Dialog", "COM5"))
        self.comboBox_EDFA2.setItemText(5, _translate("Dialog", "COM6"))
        self.comboBox_EDFA2.setItemText(6, _translate("Dialog", "COM7"))
        self.comboBox_EDFA2.setItemText(7, _translate("Dialog", "COM8"))
        self.comboBox_EDFA2.setItemText(8, _translate("Dialog", "COM9"))
        self.label_6.setText(_translate("Dialog", "DC"))
        self.comboBox_DC.setItemText(0, _translate("Dialog", "COM1"))
        self.comboBox_DC.setItemText(1, _translate("Dialog", "COM2"))
        self.comboBox_DC.setItemText(2, _translate("Dialog", "COM3"))
        self.comboBox_DC.setItemText(3, _translate("Dialog", "COM4"))
        self.comboBox_DC.setItemText(4, _translate("Dialog", "COM5"))
        self.comboBox_DC.setItemText(5, _translate("Dialog", "COM6"))
        self.comboBox_DC.setItemText(6, _translate("Dialog", "COM7"))
        self.comboBox_DC.setItemText(7, _translate("Dialog", "COM8"))
        self.comboBox_DC.setItemText(8, _translate("Dialog", "COM9"))
